#!/bin/bash

export BB_ENV_EXTRAWHITE="${BB_ENV_EXTRAWHITE} \
    ROOT_PWD \
    KEYBOARD_PROFILE \
    HOST_NAME \
    CUSTOM_DISTRO_NAME \
    CUSTOM_DISTRO_VERSION \
    NETWORK_STATIC_IP \
    WIFI_SSID \
    WIFI_PWD \
    SSH_ALLOW_ROOT \
"